export { ParticipacaoDaReceitaPropriaMunicipalAplicadaEmSaudeEC29 } from './01_participacao_da_receita_propria_municipal_aplicada_em_saudeEC29';
export { DespesaEmSaudeUtilizandoRecursosPropriosDoMunicipioPorHabDe2019 } from './02_despesa_em_saude_utilizando_recursos_proprios_do_municipio_por_hab_R$_de_2019';
export { DespesaTotalComSaudeSobResponsabilidadeDoMunicipioPorHabDe2019 } from './03_despesa_total_com_saude_sob_responsabilidade_do_municipio_por_Hab_R$_de_2019';
export { ParticipacaoDaReceitaPropriaEstadualAplicadaEmSaudeEC29 } from './04_participacao_da_receita_propria_estadual_aplicada_em_saude_EC29%';
export { DespesaEmSaudeUtilizandoRecursosPropriosDoEstadoPorHabDe2019 } from './05_despesa_em_saude_utilizando_recursos_proprios_do_estado_por_Hab_R$_de_2019';
export { DespesaTotalComSaudeSobResponsabilidadeDoEstadoPorHabDe2019 } from './06_despesa_total_com_saude_sob_responsabilidade_do_estado_por_Hab_R$_de_2019';